version: '4.0'
services:
  app:
    build: 
      context: app
    ports:
      - '5005:5005'
    volumes:
      - ./app:/flask

  nginx: 
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "5004:80"